apiVersion: v1
kind: Service
metadata:
  name: rolldice-service
spec:
  selector:
    app: rolldice
  ports:
    - name: web           
      protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP